version: '3.1'
volumes:
    mysql_db: {}

services:

  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - mysql_db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty
      - MYSQL_DATABASE=test_db
    ports:
      - 3306:3306
